### ISSUE TITLE
For linux Systems, with STM32F429i Disco. board, ST-Link V2 setup should be mentioned

### ISSUE THREAD

**Issue by hasnainvirk** [ARMmbed/example-mbedos-blinky#5]
You should add the following process in your README.md if you think it will ease the developer.

The process goes like this:
1) Clone this repo https://github.com/texane/stlink 
2) Install dependencies:
    - sudo apt-get install libusb-1.0-0-dev 
    - sudo apt-get install pkg-config
    -  sudo apt-get install auto-conf
3) Move to the repo directory and give following commands
    - ./autogen.sh
    - ./configure
    - make
    - sudo cp *.rules /etc/udev/rules.d
4) Move to the directory named 'flash'
    - make -f Makefile
    - sudo cp st-flash /usr/bin
5) Now, for flashing the board, use the following command
     - sudo st-flash write example-mbedos-blinky.bin 0x8000000

**Comment by rainierwolfcastle** [comment]
http://jira-dev0.cambridge.arm.com/browse/IOTSFW-886

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTSFW-983

**Comment by 0xc0170** [comment]
The readme is for k64f, as an example. I believe st link linux set-up has a place but not here. I'll close this, and add here ppl which can help to write this guide for st targets debugging under linux 

cc @sg- @mlnx @BlackstoneEngineering, please check the guide above, might be useful to have it somwhere
